config/routes.rb
Untitled::Application.routes.draw do
  devise_for :users,  :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }

  resources :units

  root :to => 'units#index'

  scope "/admin" do
    resources :users
  end

  get "/search" => 'units#search'
  get "/profile" => 'users#show'
  get "/matching" => 'users#matching'
  get "/roommates" => 'users#roommates'
  get "/viewuser" => 'users#viewuser'

  get "/walkscore" => 'units#walkscore'

end

app/models/unit.rb
class Unit < ActiveRecord::Base

  include Tire::Model::Search
  include Tire::Model::Callbacks
  Tire.configure { url "lisp.cs.ucsb.edu:9200" }

  belongs_to :user
  has_many :UnitPhotos
  belongs_to :city
  belongs_to :state

  geocoded_by :formatted_address
  reverse_geocoded_by :latitude, :longitude

  DEFAULT_SEARCH_SIZE = 25

  #geocoded_by :full_street_address
  #
  #def self.full_street_address
  #  string = :property_address
  #  string << " "
  #  string << City
  #end

  def self.simple_search(search_terms, options={})
    search = Tire.search Unit.tire.index.name, load:true do
      # What we're looking for
      query do
        string search_terms, fields: [:ad_headline, :ad_content]
      end

      #highlight :ad_headline, :ad_content

      # Sort results
      sort { by :created_at }

      # Results pagination / number of results per page
      page = (options[:page] || 1).to_i
      search_size = options[:per] || DEFAULT_SEARCH_SIZE
      from (page -1) * search_size
      size search_size

      #facets
      if options[:facets]
        facet('current-city') { terms :city_id }
        facet('current-state') { terms :state_id }
        facet('current-bathroom') {terms :bathrooms}
        facet('current-bedroom'){terms :bedrooms}
      end

    end
  end

  def self.advanced_search(search_conditions, search_size, options={})

    fields = [:ad_content, :city_id, :state_id, :bathrooms, :bedrooms]

    search = Tire.search Unit.tire.index.name, load:true do

      # What we're looking for
      query do
        boolean do
          fields.each do |field|
            must { string search_conditions[field], :default_operator => 'AND', :fields => [field] } if search_conditions[field].present?
          end

          rent_min = search_conditions['rent_min'].present? ? search_conditions['rent_min'] : 0
          rent_max = search_conditions['rent_max'].present? ? search_conditions['rent_max'] : 99999999

          must { range :rent_max, { gte: rent_min, lte: rent_max } }
        end

      end

      #highlight :ad_headline, :ad_content, :options => { :tag => '<strong class="highlight">' }
      #highlight *fields

      # Sort results
      sort { by :created_at }

      # Results pagination / number of results per page
      page = (options[:page] || 1).to_i
      from (page -1) * search_size
      size search_size

      highlight :ad_content, :options => { :tag => '<span>' }


      #facets
      facet('current-city') { terms :city_id }
      facet('current-state') { terms :state_id }
      facet('current-bathroom') {terms :bathrooms}
      facet('current-bedroom'){terms :bedrooms}
      end
  end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  include Tire::Model::Search
  include Yelp::V1::Review::Request
  require 'net/http'

  def index
    params[:search] ||={}

    search_size = params[:map_view] == "1" ? 500 : 25
    search = Unit.advanced_search(params[:search], search_size, page: params[:page])

    @units = search.results

    if params[:map_view]
      render 'map_view'
    else
      render 'index'
    end
  end

  def show
    @unit = Unit.find(params[:id])
    @user = current_user
  end

  def search
    redirect_to "/" and return unless params[:search].present? && params[:search][:q].present?

    search = Unit.simple_search(params[:search][:q], page: params[:page], facets: false)
    @units = search.results

    render 'index'
  end

  def walkscore

    result = Net::HTTP.get(URI.parse('http://api.walkscore.com/score?format=json&lat=' + params[:latitude] + '&lon=' + params[:longitude] + '&wsapikey=6903c6db94b91a3d32dfb5eaa9c724fd'))

    render :json => result
  end

end

app/helpers/units_helper.rb
module UnitsHelper

  def title(page_title)
    content_for :title, page_title.to_s
  end

  def tab(tab)
    content_for :tab, tab.to_s
  end


  def total_found(units)
    (units.respond_to? :total) ? "Found <em>#{units.total}</em> results, showing <em>#{units.count}</em>".html_safe : "Found <em>#{units.count}</em> results.".html_safe
  end

  def replace_search_param(original_params, name, value)
    local_params = original_params.dup
    local_params[:search] ||= {}
    local_params[:search] = local_params[:search].dup
    local_params[:search][name] = value

    local_params
  end

  def original_search(params)
    params[:search] && params[:search][:q]
  end

end

app/views/units/_advanced.html.erb
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-title">
        <div class="row">
          <div class="col-md-4 results">
            <h4>Search</h4>
          </div>
          <div class="col-md-4 col-md-offset-4" style="text-align:right;padding-right:16px;">

            <% if not request.fullpath.include? "map_view" %>

                <a href="<%=
                    if request.fullpath.include? "?"
                      request.original_url + "&map_view=1"
                    else
                      request.original_url + "?map_view=1"
                    end

                %>"><button class="btn btn-primary">Map View</button></a>

          <% else %>
                <a href="<%= request.original_url.sub! 'map_view=1', '' %>"><button class="btn btn-primary">List View</button></a>

          <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="panel-collapse collapse in" id="collapseOne">
      <div class="panel-body">
        <div class="well">
          <form id="advanced_form" action="/" method="get" role="form">
            <% if params[:map_view] %>
                <input type="hidden" name="map_view" value="1" />
            <% end %>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label for="unit-info">Keyword</label>
                  <input id="unit-ad-content" class="form-control" placeholder="Search Description" name="search[ad_content]" value="<%= params[:search][:ad_content] %>" />
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-inline">
                  <label for="unit-info">Price range</label><br />
                  <input id="unit-ad-content" class="form-control" placeholder="Rent min" name="search[rent_min]" value="<%= params[:search][:rent_min] %>" />
                  <input id="unit-ad-content" class="form-control" placeholder="Rent max" name="search[rent_max]" value="<%= params[:search][:rent_max] %>" />
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <label for="unit-info">State</label>
                <%= select_tag "search[state_id]", options_from_collection_for_select(State.order(:name), :id, :name, params[:search][:state_id]), class: "form-control", :prompt => 'Select State' %>
              </div>
              <% unless params[:search][:state_id].nil? %>
                <div class="col-md-6">
                  <label for="unit-info">City</label>
                  <%=
                      options = City.where(state_id: params[:search][:state_id]).order(:name)
                      select_tag "search[city_id]", options_from_collection_for_select(options, :id, :name, params[:search][:city_id]), class: "form-control", :prompt => "Select City"
                  %>
                </div>
              <% end %>
            </div>
            <br />
            <% if params[:map_view] %>
                <input type="hidden" name="map_view" value="1" />
           <% end %>
            <button class="btn btn-danger" type="submit">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script type='text/javascript'>
  $(document).ready(function() {
    $("select").select2();
    $("#search_state_id, #search_city_id").change(function() {
       $("#advanced_form").submit();
    });
  });
</script>

app/views/units/_facet.html.erb
<li>
  <%= link_to "<b>#{name}</b> <span class='label label-success'>#{count}</span>".html_safe, replace_search_param(params, search_option, term) %>
</li>

app/views/units/_facets.html.erb
<% if total > 0 %>
<div class="sidebar-nav" style="position:fixed">
  <div class="well">

    <div class="nav-header" style="padding-top:8px;">
      <a data-toggle="collapse" href="#bedrooms" class="btn btn-success btn-block" role="button">Bedrooms</a>
    </div>
    <div id="bedrooms" class="collapse in">
      <ul class="nav nav-list">
        <% @units.facets['current-bedroom']['terms'].each do |facet| %>
            <%= render partial: 'units/facet', locals: {term: facet['term'],
                                                        count: facet['count'],
                                                        name: facet['term'],
                                                        search_option:'bedrooms'} %>
        <% end %>
      </ul>
    </div>

    <div class="nav-header">
      <a data-toggle="collapse" href="#bathrooms" class="btn btn-success btn-block" role="button">Bathrooms</a>
    </div>
    <div id="bathrooms" class="collapse in">
      <ul class="nav nav-list">
        <% @units.facets['current-bathroom']['terms'].each do |facet| %>
            <%= render partial: 'units/facet', locals: {term: facet['term'],
                                                        count: facet['count'],
                                                        name: facet['term'],
                                                        search_option:'bathrooms'} %>
        <% end %>
      </ul>
    </div>

  </div>
</div>
<% end %>

app/views/units/_highlight.html.erb
<% %w(ad_headline ad_content).each do |field| %>
  <% if highlight.send(field) %>
    <b>#{field.capitalize}:</b>
    <%= highlight.send(field).join(' ... ').html_safe %>
    <br/>
  <% end %>
<% end %>

app/views/units/_mapfacets.html.erb
<% if total > 0 %>
    <div class="sidebar-nav">
      <div class="well">

        <div class="nav-header" style="padding-top:8px;">
          <a data-toggle="collapse" href="#bedrooms" class="btn btn-success btn-block" role="button">Bedrooms</a>
        </div>
        <div id="bedrooms" class="collapse">
          <ul class="nav nav-list">
            <% @units.facets['current-bedroom']['terms'].each do |facet| %>
                <%= render partial: 'units/facet', locals: {term: facet['term'],
                                                            count: facet['count'],
                                                            name: facet['term'],
                                                            search_option:'bedrooms'} %>
            <% end %>
          </ul>
        </div>

        <div class="nav-header">
          <a data-toggle="collapse" href="#bathrooms" class="btn btn-success btn-block" role="button">Bathrooms</a>
        </div>
        <div id="bathrooms" class="collapse">
          <ul class="nav nav-list">
            <% @units.facets['current-bathroom']['terms'].each do |facet| %>
                <%= render partial: 'units/facet', locals: {term: facet['term'],
                                                            count: facet['count'],
                                                            name: facet['term'],
                                                            search_option:'bathrooms'} %>
            <% end %>
          </ul>
        </div>

      </div>
    </div>
<% end %>

app/views/units/_search.html.erb
<%= form_tag(search_path, id: 'new_search', class: 'navbar-form navbar-left', method: 'get') do %>
  <div class="form-group">
    <input class="form-control" id="units_search" name="search[q]" placeholder="Search units..." type="text" value="<%= original_search(params) %>"></input>
  </div>
  <button class="btn btn-danger" type="submit">
    Search
  </button>
<% end %>

app/views/units/_serp.html.erb
<style type="text/css">
    @import url(http://fonts.googleapis.com/css?family=Lato:400,700);
    body
    {
        font-family: 'Lato', 'sans-serif';
    }
    .profile
    {
        min-height: 355px;
        display: inline-block;
    }
    figcaption.ratings
    {
        margin-top:20px;
    }
    figcaption.ratings a
    {
        color:#f1c40f;
        font-size:11px;
    }
    figcaption.ratings a:hover
    {
        color:#f39c12;
        text-decoration:none;
    }
    .divider
    {
        border-top:1px solid rgba(0,0,0,0.1);
    }
    .emphasis
    {
        border-top: 4px solid transparent;
    }
    .emphasis:hover
    {
        border-top: 4px solid #1abc9c;
    }
    .emphasis h2
    {
        margin-bottom:0;
    }
    span.tags
    {
        background: #1abc9c;
        border-radius: 2px;
        color: #f5f5f5;
        font-weight: bold;
        padding: 2px 4px;
    }
    .dropdown-menu
    {
        background-color: #34495e;
        box-shadow: none;
        -webkit-box-shadow: none;
        width: 250px;
        margin-left: -125px;
        left: 50%;
    }
    .dropdown-menu .divider
    {
        background:none;
    }
    .dropdown-menu>li>a
    {
        color:#f5f5f5;
    }
    .dropup .dropdown-menu
    {
        margin-bottom:10px;
    }
    .dropup .dropdown-menu:before
    {
        content: "";
        border-top: 10px solid #34495e;
        border-right: 10px solid transparent;
        border-left: 10px solid transparent;
        position: absolute;
        bottom: -10px;
        left: 50%;
        margin-left: -10px;
        z-index: 10;
    }
</style>
<% @units.each_with_hit do |unit, hit| %>

    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
    <div class="">
      <div class="">
        <div class="">
          <div class="well profile">
            <h2><%= link_to truncate(unit.ad_headline, length: 50), unit_url(unit) %></h2>
            <br />
            <div class="row">
              <div class="col-xs-6 col-sm-6">
                <p class="description">
                    <strong>Description: </strong>
                  <% unless hit['highlight'].nil? %>
                      <%=raw hit['highlight']['ad_content'].map(&:inspect).join(',').gsub('"', '') if hit['highlight']['ad_content'] %>
                  <% else %>
                      <%= truncate(unit.ad_content, length: 300, omission: '... (continued)') %>
                  <% end %>

                </p>
                <% if unit.deposit_max != nil %>
                    <p><strong>Security Deposit:</strong> $<%=unit.deposit_max%></p>
                <% end %>

                <% if unit.lease_application_fee != nil %>
                    <p><strong>Application Fee:</strong> $<%=unit.lease_application_fee%></p>
                <% end %>
                <% if unit.property_address != nil %>

                      <p><strong>Address:</strong> <%=unit.property_address%>, <%=unit.property_postal_code %></p>
                <% end %>
                <% if unit.city.name != nil and unit.state.name != nil %>
                    <p><strong>Location:</strong> <%=unit.city.name %>, <%=unit.state.name %></p>
                <% end %>

                <% if unit.square_foot_min != nil %>
                      <p><strong>Square Footage:</strong> <%=unit.square_foot_min%></p>

                <% end %>
                <% if unit.amenities != '' %>
                      <p><strong>Amenities:</strong> <%=unit.amenities%></p>

                <% end %>

                <p><strong>Posted by:</strong> <%=unit.user.email %></p>


              </div>
              <div class="col-xs-4 col-sm-4 text-center">
                <figure>
                  <% unit.UnitPhotos.take(1).each do |unit_photos| %>
                      <img border="0" src="<%= unit_photos.image_url %>" width="350" height="262">
                  <% end %>

                </figure>
              </div>
            </div>
            <div class="col-xs-12 divider text-center">
              <div class="col-xs-12 col-sm-4 emphasis">
                <h2><strong> $ <%=unit.rent_max%> </strong></h2>
                <p><small>Rent</small></p>

              </div>
              <div class="col-xs-12 col-sm-4 emphasis">
                <h2><strong><%=unit.bedrooms.nil? ? "-" : unit.bedrooms %></strong></h2>
                <p><small>Bedrooms</small></p>
              </div>
              <div class="col-xs-12 col-sm-4 emphasis">
                <h2><strong><%=unit.bathrooms.nil? ? "-" : unit.bathrooms%></strong></h2>
                <p><small>Bathrooms</small></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <hr />
<% end %>

app/views/units/index.html.erb
  <% title "Homepage" %>

  <div class="content">

    <div class="panel panel-default">

      <div class="panel-body">

        <div class="row">
          <div class="col-md-12">
            <%= render partial: 'units/advanced' %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 results">
            <%= total_found(@units) %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <%= render partial:'units/serp' %>
            <tr>
              <td colspan="2">
                <%= paginate @units %>
              </td>
            </tr>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/units/map_view.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


<% title "Homepage" %>
  <div class="content">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <%= render partial: 'units/advanced' %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 results">
            <%= total_found(@units) %>
          </div>

        </div>
        <div class="row">
          <div class="col-md-12">

            <div style='width: 100%;'>
              <div id="map" style='width: 100%; height: 550px;'></div>
            </div>
            <script type="text/javascript">

                $('#map').gmap().bind('init', function(ev, map) {

                    <% @units.each do |unit| %>
                    $('#map').gmap('addMarker', {'position': '<%= unit.latitude %>,<%= unit.longitude %>', 'bounds': true}).click(function() {
                        $('#map').gmap('openInfoWindow', {'content': '<%= link_to unit.formatted_address, unit_url(unit) %>'}, this);
                    });
                    <% end %>

                    if(!localStorage.getItem("zoom"))
                    {
                        $("#map").gmap('option', 'zoom', 7);
                    }
                    else
                    {
                        $("#map").gmap('option', 'zoom', parseInt(localStorage.getItem("zoom")));
                    }

                    $(map).addEventListener('zoom_changed', function() {
                        zoomLevel = map.getZoom();
                        localStorage.setItem("zoom", zoomLevel);
                    });

                });
            </script>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/units/show.html.erb
<% title "Unit Listing" %>

<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<style type="text/css">
    /* styles for displaying scores from the Walk Score API */
    .walkscore-scoretext, .walkscore-noscoretext {
        position: relative;
        top: -2px;
        color: #b14900;
        margin-left: 3px;
        text-decoration: underline;
        font-weight: normal;
    }
    .walkscore-scoretext {
        margin-left: 7px;
        font-weight: bold;
        font-size: 24px;
        text-decoration:none;
        top: 5px;
    }
    #walkscore-div a {
        text-decoration:none;
    }

    /* styles for the info icon */
    #ws_info {
        position: relative;
        top: -5px;
        margin-left: 4px;
    }
</style>

<div class="content">
  <div class="panel panel-default">
    <div class="panel-body">
      <table class="table table-striped">
        <tr>
          <td class="col-md-2">
            <b>Ad Title</b>
          </td>
          <td>
            <%= @unit.ad_headline %>
          </td>
        </tr>
        <tr>
          <td>
            <b>Map</b>
          </td>
          <td>
            <div id="walkscore-div">&nbsp;</div>
            <div style='width: 800px;'>
              <div id="map" style='width: 800px; height: 400px;'></div>
            </div>
            <script type="text/javascript">
                $('#map').gmap().bind('init', function(ev, map)
                {
                    $('#map').gmap('addMarker',
                            {'position': '<%= @unit.latitude %>,<%= @unit.longitude %>', 'bounds': true}).click(function()
                            {$('#map').gmap('openInfoWindow', {'content': '<%= @unit.formatted_address %>'}, this);
                            });
                    $("#map").gmap('option', 'zoom', 14);
                });
            </script>
          </td>
        </tr>
        <tr>
          <td>
            <b>Description</b>
          </td>
          <td>
            <%= @unit.ad_content %>
          </td>
        </tr>
        <tr>
          <td>
            <b>Photos</b>
          </td>
          <td>
            <div class="row">

            <% @unit.UnitPhotos.each do |unit_photos| %>
                  <div class="col-lg-4">
                    <a class="fancybox" href="<%= unit_photos.image_url %>" data-fancybox-group="gallery" title=""><img height="150" width="242"  src="<%= unit_photos.image_url %>" alt="" /></a>
                  </div>
              <% end %>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <b>Interested Users</b>
          </td>
          <td>
            <div class="row">
              <h3><img src="http://graph.facebook.com/1059545421/picture" width="100" height="80">
                <a href="/viewuser?id=2612">tww_91@yahoo.com</a>
              </h3>
              <h4 style="display:none"><img src="<%= @user.fb_photo_url %>" width="100" height="80">
                <a href="/viewuser?id=<%= @user.id %>"><%= @user.email %></a>
              </h4>
              
              <br><button class="btn btn-success" role="button">I'm Interested!</button>
              
            </div>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
      $('.fancybox').fancybox();

        $("button").click(function(){
            $("h4").toggle();
        });
      var url="/walkscore?latitude=" + <%=@unit.latitude %> + "&longitude=" + <%=@unit.longitude %>;
      $.ajax( {
                  url: url,
                  type:'GET',
                  success: function(data) { displayWalkScores((data)); },
                  error: function(){ displayWalkScores(""); }
              }
      );

      //to demonstrate all of our formatting options, we'll pass the json on to a series of display functions.
      //in practice, you'll only need one of these, and the ajax call could call it directly as it's onSuccess callback
      function displayWalkScores(jsonStr) {
          displayWalkScore(jsonStr);
      }

      //show the walk score -- inserts walkscore html into the page.  Also needs CSS from top of file
      function displayWalkScore(json) {

          //if we got a score
          if (json && json.status == 1) {
              var htmlStr = '<a target="_blank" href="' + json.ws_link + '"><img src="' + json.logo_url + '" /><span class="walkscore-scoretext">' + json.walkscore + '</span></a>';
          }
          //if no score was available
          else if (json && json.status == 2) {
              var htmlStr = '<a target="_blank" href="' + json.ws_link + '"><img src="' + json.logo_url + '" /> <span class="walkscore-noscoretext">Get Score</span></a>';
          }
          //if didn't even get a json response
          else {
              var htmlStr = '<a target="_blank" href="http://www.walkscore.com"><img src="http://cdn.walk.sc/images/api-logo.gif" /> <span class="walkscore-noscoretext">Get Score</span></a> ';
          }
          var infoIconHtml = '<span id="ws_info"><a href="http://www.walkscore.com/live-more" target="_blank"><img src="http://cdn2.walk.sc/2/images/api-more-info.gif" width="13" height="13"" /></a></span>';

          //if you want to wrap extra tags around the html, can do that here before inserting into page element
          htmlStr = '<p>' + htmlStr + infoIconHtml + '</p>';

          //insert our new content into the container div:
          $("#walkscore-div").html(htmlStr);
      }
  });
</script>