config/routes.rb
Untitled::Application.routes.draw do
  devise_for :users,  :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }

  resources :units

  root :to => 'units#index'

  scope "/admin" do
    resources :users
  end

  get "/search" => 'units#search'
  get "/profile" => 'users#show'
  get "/matching" => 'users#matching'
  get "/roommates" => 'users#roommates'
  get "/viewuser" => 'users#viewuser'

  get "/walkscore" => 'units#walkscore'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all"  %>
  <%= javascript_include_tag "application"  %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %> <!-- Favicon -->

</head>

<body role="document">

<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <%= link_to image_tag("logo.fw.png"), "/", id: "", class: "navbar-brand" %> <!-- LOGO -->

    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="<%= controller.class == UnitsController and controller.action_name == 'index' ? 'active' : '' %>"><a href="/">Home</a></li>
        <% if user_signed_in? %>
            <li class="<%= request.path == roommates_path ? 'active' : '' %>"><%= link_to "Find Roommates", roommates_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to('Profile', profile_path) %></li>
                <li><%= link_to('Matching', matching_path) %></li>
                <li class="divider"></li>
                <li class="dropdown-header"></li>
                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
            <li class="<%= request.path == new_user_session_path ? 'active' : '' %>"><%= link_to "Sign in", new_user_session_path %></li>
            <li class="<%= request.path == new_user_registration_path ? 'active' : '' %>"><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

  <% if @units.respond_to?(:facets) && @units.facets.present? %>
      <div class="col-md-2">
        <%= render partial: 'units/facets', locals: {total: @units.total} %>
      </div>
  <% end %>

<div class="container container-space container-fluid" role="main">

  <% if notice %>
      <div class="row">
        <div class="span4 alert alert-info"><%= notice %></div>
      </div>
  <% end %>
  <% if alert %>
      <div class="row">
        <div class="span4 alert alert-danger"><%= alert %></div>
      </div>
  <% end %>

  <%= yield %>

</div>



</body>
</html>